ollama_image_analysis:
  fields:
    prompt:
      example: |
        You are a security agent and analyze the following camera image. Your focus is to identify irregularities. Please list all irregularities.
      required: true
      selector:
        text:
          multiline: true
    image_path:
      example: /x/y/camera_image.jpg
      required: true
      selector:
        text:
    model:
      example: llava
      default: llava
      required: false
      selector:
        text:
